set_property PACKAGE_PIN P14 [get_ports {LED[7]}]
set_property PACKAGE_PIN N17 [get_ports {LED[6]}]
set_property PACKAGE_PIN W15 [get_ports {LED[5]}]
set_property PACKAGE_PIN R14 [get_ports {LED[4]}]
set_property PACKAGE_PIN W19 [get_ports {LED[3]}]
set_property PACKAGE_PIN Y16 [get_ports {LED[2]}]
set_property PACKAGE_PIN Y14 [get_ports {LED[1]}]
set_property PACKAGE_PIN Y17 [get_ports {LED[0]}]
set_property PACKAGE_PIN W18 [get_ports {Select[0]}]
set_property PACKAGE_PIN V15 [get_ports {Select[1]}]
set_property PACKAGE_PIN W14 [get_ports {Select[2]}]
set_property PACKAGE_PIN P18 [get_ports {Select[3]}]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Select[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

set_property PACKAGE_PIN F16 [get_ports {Select[4]}]
set_property PACKAGE_PIN J18 [get_ports {Select[5]}]
set_property PACKAGE_PIN M20 [get_ports {Select[7]}]
set_property PACKAGE_PIN L19 [get_ports {Select[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports {LED2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED2[7]}]
set_property PACKAGE_PIN F19 [get_ports {LED2[7]}]
set_property PACKAGE_PIN M19 [get_ports {LED2[6]}]
set_property PACKAGE_PIN H18 [get_ports {LED2[5]}]
set_property PACKAGE_PIN F20 [get_ports {LED2[4]}]
set_property PACKAGE_PIN F17 [get_ports {LED2[3]}]
set_property PACKAGE_PIN G19 [get_ports {LED2[2]}]
set_property PACKAGE_PIN L20 [get_ports {LED2[1]}]
set_property PACKAGE_PIN G20 [get_ports {LED2[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property PACKAGE_PIN R17 [get_ports rst]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
create_generated_clock -name u_multiLED/insFrequencyDivider/clk_out -source [get_ports clk] -divide_by 50000 [get_pins u_multiLED/insFrequencyDivider/clk_out_reg/Q]

set_property IOSTANDARD LVCMOS18 [get_ports btn]
set_property PACKAGE_PIN T17 [get_ports btn]
