webtalk_init -webtalk_dir D:/Programming/Github/MIPS-Multi-Cycle-MicroSystem/MIPS-Multi-Cycle-MicroSystem.sim/sim_1/behav/xsim/xsim.dir/timeCounterSIM_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 13 17:25:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "254044c3-3622-474f-9402-196f4424af39" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "33ef219c4e164fd59ce693cc9c52d297" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7828_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3669026748 -regid "" -xml D:/Programming/Github/MIPS-Multi-Cycle-MicroSystem/MIPS-Multi-Cycle-MicroSystem.sim/sim_1/behav/xsim/xsim.dir/timeCounterSIM_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Programming/Github/MIPS-Multi-Cycle-MicroSystem/MIPS-Multi-Cycle-MicroSystem.sim/sim_1/behav/xsim/xsim.dir/timeCounterSIM_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Programming/Github/MIPS-Multi-Cycle-MicroSystem/MIPS-Multi-Cycle-MicroSystem.sim/sim_1/behav/xsim/xsim.dir/timeCounterSIM_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
